# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreateTaskRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'acl': 'list[str]',
        'task_versions': 'list[CreateTaskVersionRequest]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'acl': 'acl',
        'task_versions': 'taskVersions'
    }

    def __init__(self, name=None, description=None, acl=None, task_versions=None):  # noqa: E501
        """CreateTaskRequest - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._acl = None
        self._task_versions = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        if acl is not None:
            self.acl = acl
        if task_versions is not None:
            self.task_versions = task_versions

    @property
    def name(self):
        """Gets the name of this CreateTaskRequest.  # noqa: E501

        User-defined name of the task  # noqa: E501

        :return: The name of this CreateTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateTaskRequest.

        User-defined name of the task  # noqa: E501

        :param name: The name of this CreateTaskRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 0:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this CreateTaskRequest.  # noqa: E501

        User-defined description of the task  # noqa: E501

        :return: The description of this CreateTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateTaskRequest.

        User-defined description of the task  # noqa: E501

        :param description: The description of this CreateTaskRequest.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 4096:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `4096`")  # noqa: E501
        if description is not None and len(description) < 0:
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def acl(self):
        """Gets the acl of this CreateTaskRequest.  # noqa: E501

        Access Control List  # noqa: E501

        :return: The acl of this CreateTaskRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._acl

    @acl.setter
    def acl(self, acl):
        """Sets the acl of this CreateTaskRequest.

        Access Control List  # noqa: E501

        :param acl: The acl of this CreateTaskRequest.  # noqa: E501
        :type: list[str]
        """

        self._acl = acl

    @property
    def task_versions(self):
        """Gets the task_versions of this CreateTaskRequest.  # noqa: E501

        List of task versions  # noqa: E501

        :return: The task_versions of this CreateTaskRequest.  # noqa: E501
        :rtype: list[CreateTaskVersionRequest]
        """
        return self._task_versions

    @task_versions.setter
    def task_versions(self, task_versions):
        """Sets the task_versions of this CreateTaskRequest.

        List of task versions  # noqa: E501

        :param task_versions: The task_versions of this CreateTaskRequest.  # noqa: E501
        :type: list[CreateTaskVersionRequest]
        """

        self._task_versions = task_versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateTaskRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateTaskRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
