# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobOperationParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'folder_copy': 'FolderCopyOperationParameters'
    }

    attribute_map = {
        'folder_copy': 'folderCopy'
    }

    def __init__(self, folder_copy=None):  # noqa: E501
        """JobOperationParameters - a model defined in Swagger"""  # noqa: E501

        self._folder_copy = None
        self.discriminator = None

        if folder_copy is not None:
            self.folder_copy = folder_copy

    @property
    def folder_copy(self):
        """Gets the folder_copy of this JobOperationParameters.  # noqa: E501


        :return: The folder_copy of this JobOperationParameters.  # noqa: E501
        :rtype: FolderCopyOperationParameters
        """
        return self._folder_copy

    @folder_copy.setter
    def folder_copy(self, folder_copy):
        """Sets the folder_copy of this JobOperationParameters.


        :param folder_copy: The folder_copy of this JobOperationParameters.  # noqa: E501
        :type: FolderCopyOperationParameters
        """

        self._folder_copy = folder_copy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobOperationParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobOperationParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
