# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ObjectStoreAccess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'str',
        'aws_s3_temporary_upload_credentials': 'AwsS3TemporaryUploadCredentials'
    }

    attribute_map = {
        'session_id': 'sessionId',
        'aws_s3_temporary_upload_credentials': 'awsS3TemporaryUploadCredentials'
    }

    def __init__(self, session_id=None, aws_s3_temporary_upload_credentials=None):  # noqa: E501
        """ObjectStoreAccess - a model defined in Swagger"""  # noqa: E501

        self._session_id = None
        self._aws_s3_temporary_upload_credentials = None
        self.discriminator = None

        if session_id is not None:
            self.session_id = session_id
        if aws_s3_temporary_upload_credentials is not None:
            self.aws_s3_temporary_upload_credentials = aws_s3_temporary_upload_credentials

    @property
    def session_id(self):
        """Gets the session_id of this ObjectStoreAccess.  # noqa: E501


        :return: The session_id of this ObjectStoreAccess.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this ObjectStoreAccess.


        :param session_id: The session_id of this ObjectStoreAccess.  # noqa: E501
        :type: str
        """

        self._session_id = session_id

    @property
    def aws_s3_temporary_upload_credentials(self):
        """Gets the aws_s3_temporary_upload_credentials of this ObjectStoreAccess.  # noqa: E501


        :return: The aws_s3_temporary_upload_credentials of this ObjectStoreAccess.  # noqa: E501
        :rtype: AwsS3TemporaryUploadCredentials
        """
        return self._aws_s3_temporary_upload_credentials

    @aws_s3_temporary_upload_credentials.setter
    def aws_s3_temporary_upload_credentials(self, aws_s3_temporary_upload_credentials):
        """Sets the aws_s3_temporary_upload_credentials of this ObjectStoreAccess.


        :param aws_s3_temporary_upload_credentials: The aws_s3_temporary_upload_credentials of this ObjectStoreAccess.  # noqa: E501
        :type: AwsS3TemporaryUploadCredentials
        """

        self._aws_s3_temporary_upload_credentials = aws_s3_temporary_upload_credentials

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ObjectStoreAccess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectStoreAccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
