# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductUsage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'amount': 'float',
        'unit': 'str',
        'i_credit': 'float'
    }

    attribute_map = {
        'type': 'type',
        'amount': 'amount',
        'unit': 'unit',
        'i_credit': 'iCredit'
    }

    def __init__(self, type=None, amount=None, unit=None, i_credit=None):  # noqa: E501
        """ProductUsage - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._amount = None
        self._unit = None
        self._i_credit = None
        self.discriminator = None

        self.type = type
        self.amount = amount
        self.unit = unit
        if i_credit is not None:
            self.i_credit = i_credit

    @property
    def type(self):
        """Gets the type of this ProductUsage.  # noqa: E501


        :return: The type of this ProductUsage.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ProductUsage.


        :param type: The type of this ProductUsage.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def amount(self):
        """Gets the amount of this ProductUsage.  # noqa: E501


        :return: The amount of this ProductUsage.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ProductUsage.


        :param amount: The amount of this ProductUsage.  # noqa: E501
        :type: float
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def unit(self):
        """Gets the unit of this ProductUsage.  # noqa: E501


        :return: The unit of this ProductUsage.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this ProductUsage.


        :param unit: The unit of this ProductUsage.  # noqa: E501
        :type: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def i_credit(self):
        """Gets the i_credit of this ProductUsage.  # noqa: E501


        :return: The i_credit of this ProductUsage.  # noqa: E501
        :rtype: float
        """
        return self._i_credit

    @i_credit.setter
    def i_credit(self, i_credit):
        """Sets the i_credit of this ProductUsage.


        :param i_credit: The i_credit of this ProductUsage.  # noqa: E501
        :type: float
        """

        self._i_credit = i_credit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductUsage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
