# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SystemHealthResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'HealthCheckStatuses',
        'details': 'list[ServiceHealthResponse]'
    }

    attribute_map = {
        'status': 'status',
        'details': 'details'
    }

    def __init__(self, status=None, details=None):  # noqa: E501
        """SystemHealthResponse - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._details = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if details is not None:
            self.details = details

    @property
    def status(self):
        """Gets the status of this SystemHealthResponse.  # noqa: E501


        :return: The status of this SystemHealthResponse.  # noqa: E501
        :rtype: HealthCheckStatuses
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SystemHealthResponse.


        :param status: The status of this SystemHealthResponse.  # noqa: E501
        :type: HealthCheckStatuses
        """

        self._status = status

    @property
    def details(self):
        """Gets the details of this SystemHealthResponse.  # noqa: E501

        Service health details  # noqa: E501

        :return: The details of this SystemHealthResponse.  # noqa: E501
        :rtype: list[ServiceHealthResponse]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this SystemHealthResponse.

        Service health details  # noqa: E501

        :param details: The details of this SystemHealthResponse.  # noqa: E501
        :type: list[ServiceHealthResponse]
        """

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemHealthResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemHealthResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
