# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UpdateTaskVersionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'description': 'str',
        'execution': 'Execution',
        'acl': 'list[str]'
    }

    attribute_map = {
        'version': 'version',
        'description': 'description',
        'execution': 'execution',
        'acl': 'acl'
    }

    def __init__(self, version=None, description=None, execution=None, acl=None):  # noqa: E501
        """UpdateTaskVersionRequest - a model defined in Swagger"""  # noqa: E501

        self._version = None
        self._description = None
        self._execution = None
        self._acl = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if description is not None:
            self.description = description
        if execution is not None:
            self.execution = execution
        if acl is not None:
            self.acl = acl

    @property
    def version(self):
        """Gets the version of this UpdateTaskVersionRequest.  # noqa: E501

        User-defined version of task version  # noqa: E501

        :return: The version of this UpdateTaskVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this UpdateTaskVersionRequest.

        User-defined version of task version  # noqa: E501

        :param version: The version of this UpdateTaskVersionRequest.  # noqa: E501
        :type: str
        """
        if version is not None and len(version) > 255:
            raise ValueError("Invalid value for `version`, length must be less than or equal to `255`")  # noqa: E501
        if version is not None and len(version) < 0:
            raise ValueError("Invalid value for `version`, length must be greater than or equal to `0`")  # noqa: E501

        self._version = version

    @property
    def description(self):
        """Gets the description of this UpdateTaskVersionRequest.  # noqa: E501

        User-defined description of task version  # noqa: E501

        :return: The description of this UpdateTaskVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateTaskVersionRequest.

        User-defined description of task version  # noqa: E501

        :param description: The description of this UpdateTaskVersionRequest.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 4096:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `4096`")  # noqa: E501
        if description is not None and len(description) < 0:
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def execution(self):
        """Gets the execution of this UpdateTaskVersionRequest.  # noqa: E501


        :return: The execution of this UpdateTaskVersionRequest.  # noqa: E501
        :rtype: Execution
        """
        return self._execution

    @execution.setter
    def execution(self, execution):
        """Sets the execution of this UpdateTaskVersionRequest.


        :param execution: The execution of this UpdateTaskVersionRequest.  # noqa: E501
        :type: Execution
        """

        self._execution = execution

    @property
    def acl(self):
        """Gets the acl of this UpdateTaskVersionRequest.  # noqa: E501


        :return: The acl of this UpdateTaskVersionRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._acl

    @acl.setter
    def acl(self, acl):
        """Sets the acl of this UpdateTaskVersionRequest.


        :param acl: The acl of this UpdateTaskVersionRequest.  # noqa: E501
        :type: list[str]
        """

        self._acl = acl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateTaskVersionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateTaskVersionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
