# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserAggregatedUsage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'User',
        'i_credit': 'float',
        'usages': 'list[ProductUsage]'
    }

    attribute_map = {
        'user': 'user',
        'i_credit': 'iCredit',
        'usages': 'usages'
    }

    def __init__(self, user=None, i_credit=None, usages=None):  # noqa: E501
        """UserAggregatedUsage - a model defined in Swagger"""  # noqa: E501

        self._user = None
        self._i_credit = None
        self._usages = None
        self.discriminator = None

        if user is not None:
            self.user = user
        if i_credit is not None:
            self.i_credit = i_credit
        if usages is not None:
            self.usages = usages

    @property
    def user(self):
        """Gets the user of this UserAggregatedUsage.  # noqa: E501


        :return: The user of this UserAggregatedUsage.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserAggregatedUsage.


        :param user: The user of this UserAggregatedUsage.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def i_credit(self):
        """Gets the i_credit of this UserAggregatedUsage.  # noqa: E501


        :return: The i_credit of this UserAggregatedUsage.  # noqa: E501
        :rtype: float
        """
        return self._i_credit

    @i_credit.setter
    def i_credit(self, i_credit):
        """Sets the i_credit of this UserAggregatedUsage.


        :param i_credit: The i_credit of this UserAggregatedUsage.  # noqa: E501
        :type: float
        """

        self._i_credit = i_credit

    @property
    def usages(self):
        """Gets the usages of this UserAggregatedUsage.  # noqa: E501


        :return: The usages of this UserAggregatedUsage.  # noqa: E501
        :rtype: list[ProductUsage]
        """
        return self._usages

    @usages.setter
    def usages(self, usages):
        """Sets the usages of this UserAggregatedUsage.


        :param usages: The usages of this UserAggregatedUsage.  # noqa: E501
        :type: list[ProductUsage]
        """

        self._usages = usages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAggregatedUsage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAggregatedUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
