# coding: utf-8

"""
    Illumina Connected Analysis

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WorkflowArgument(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'value': 'str',
        'json': 'object',
        'options': 'str'
    }

    attribute_map = {
        'name': 'name',
        'value': 'value',
        'json': 'json',
        'options': 'options'
    }

    def __init__(self, name=None, value=None, json=None, options=None):  # noqa: E501
        """WorkflowArgument - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._value = None
        self._json = None
        self._options = None
        self.discriminator = None

        self.name = name
        if value is not None:
            self.value = value
        if json is not None:
            self.json = json
        if options is not None:
            self.options = options

    @property
    def name(self):
        """Gets the name of this WorkflowArgument.  # noqa: E501

        Name of the argument key  # noqa: E501

        :return: The name of this WorkflowArgument.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkflowArgument.

        Name of the argument key  # noqa: E501

        :param name: The name of this WorkflowArgument.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 128:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `128`")  # noqa: E501
        if name is not None and len(name) < 0:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this WorkflowArgument.  # noqa: E501

        A simple string value for the argument. Cannot provide both Value and Json at the same time.  # noqa: E501

        :return: The value of this WorkflowArgument.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this WorkflowArgument.

        A simple string value for the argument. Cannot provide both Value and Json at the same time.  # noqa: E501

        :param value: The value of this WorkflowArgument.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def json(self):
        """Gets the json of this WorkflowArgument.  # noqa: E501

        A JSON value for the argument. Cannot provide both Value and Json at the same time.  # noqa: E501

        :return: The json of this WorkflowArgument.  # noqa: E501
        :rtype: object
        """
        return self._json

    @json.setter
    def json(self, json):
        """Sets the json of this WorkflowArgument.

        A JSON value for the argument. Cannot provide both Value and Json at the same time.  # noqa: E501

        :param json: The json of this WorkflowArgument.  # noqa: E501
        :type: object
        """

        self._json = json

    @property
    def options(self):
        """Gets the options of this WorkflowArgument.  # noqa: E501

        Comma separated list of options for the argument: Required, Overridable, Writable, Json, Optional, ReadOnly, Final  Some combinations of options are considered errors, like Required/Optional, Overridable/Final, Writable/ReadOnly, etc.  # noqa: E501

        :return: The options of this WorkflowArgument.  # noqa: E501
        :rtype: str
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this WorkflowArgument.

        Comma separated list of options for the argument: Required, Overridable, Writable, Json, Optional, ReadOnly, Final  Some combinations of options are considered errors, like Required/Optional, Overridable/Final, Writable/ReadOnly, etc.  # noqa: E501

        :param options: The options of this WorkflowArgument.  # noqa: E501
        :type: str
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowArgument, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowArgument):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
