# coding: utf-8

# flake8: noqa
"""
    Platform Services API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from ilmn_platform.models.credential_to import CredentialTO
from ilmn_platform.models.custom_credentials_to import CustomCredentialsTO
